general:
    data_type: raw
    run: DLSraw

    plot_sample: True
    plot_reset: True
    plot_combined: True

all:
    output: &output /Users/ben/PostDoc/P2M_HDF5/Data_0918/Coarse_scan

raw:
    #input: /Users/ben/PostDoc/P2M_HDF5/Data_lab/VRST/VRST18k1to21k2_271p_AV_02_dscrmbld_DLSraw.h5
    #input: /Users/ben/PostDoc/P2M_HDF5/Data_lab/VRSTfromVin_8p1kto32k_AD_240frames_DLSraw.h5
    input: /Users/ben/PostDoc/P2M_HDF5/2018.05.23_AD_00_descrambledDLSraw.h5
    metadata_fname: null

    output: *output

    measurement: adccal

    interactive: True
    
    viewer:
        err_below: -0.1

    adc: null
    frame: null
    col: 100
    row: [0, 1484, 7]

    #method: [viewer]
    method: [image, plot_coarse-fine_vs_image]


    viewer:
        err_below: -0.1

gathered:
    input: *output
    output: *output

    measurement: adccal

    adc: 0
    frame: null
    col: 100
    row: null

    interactive: True
    
    method: [plot, hist, hist_2d]
    #method: [plot_sample_vs_reset]

processed:
    input: *output
    output: *output

    measurement: adccal

    adc: 0
    frame: null
    col: 100
    row: null
    
    interactive: True

    method: [plot_residuals]

correction:
    input: /Users/ben/PostDoc/P2M_HDF5/Data_0918
    output: /Users/ben/PostDoc/P2M_HDF5/Data_0918

    measurement: adccal

    adc: 6
    frame: null
    col: 200
    row: 100

    interactive: False

    method: [plot]
