general:
    data_type: corrected

    run: DLSraw

    plot_sample: True
    plot_reset: True
    plot_combined: True

all:
    output: &output /Volumes/LACIE_SHARE/Percival/Data_lab_october18
raw:
    input: /Volumes/LACIE_SHARE/Percival/Data_lab_october18/Coarse_scan/crs-scan_Vin=30400_DLSraw.h5

    metadata_fname: null

    output: *output

    measurement: adccal

    interactive: True
    
    viewer:
        err_below: -0.1

    adc: null
    frame: 8
    col: 500
    row: 100

    interactive: True
    method: [plot_coarse-fine_vs_image]

    viewer:
      err_below: -0.1
    #method: [image, plot_coarse-fine_vs_image, viewer]

gathered:
    input: *output
    output: *output

    measurement: adccal

    adc: 0
    frame: null
    col: 60
    row: 10
    interactive: False

    interactive: True
    
    method: [plot, hist, hist_2d]
    #method: [plot_sample_vs_reset]

processed:
    input: *output
    output: *output

    measurement: adccal

    adc: 0
    frame: null
    col: 100
    row: 100

    interactive: false
    method: [viewer]
    viewer:
        all_cols: True


corrected:
    input: *output
    output: *output

    measurement: adccal

    adc: 2
    frame: 4
    col: 61
    row: 10

    interactive: True

    method: [viewer]

    plot:
        all_cols: False
    viewer:
        all_cols: True
