general:
    run_type: process
    n_cols: 32

    measurement: adccal

    run: DLSraw

    n_processes: 1

all:
    input: &input /Users/ben/PostDoc/P2M_HDF5 
    output: &output /Users/ben/PostDoc/P2M_HDF5

gather:
    method: file_per_vin_and_register_file

    input: *input
    output: *output

process:
    method: process_adccal_default

    input: *output
    output: *output

