general:
    run_type: correction
    n_cols: 32

    measurement: adccal

    run: &run DLSraw

    n_processes: 1

all:
    input: &input /Users/ben/PostDoc/P2M_HDF5/Data_0918/Coarse_scan
    output: &output /Users/ben/PostDoc/P2M_HDF5/Data_0918/Coarse_scan
    input_coarse:  &input_coarse /Users/ben/PostDoc/P2M_HDF5/Data_0918/Coarse_scan
    input_fine: &input_fine /Users/ben/PostDoc/P2M_HDF5/Data_0918/Fine_scan
    

gather:
    method: file_per_vin_and_register_file

    input: *input
    output: *output
    input_coarse: *input_coarse
    input_fine: *input_fine

    descramble_tcpdump:
        descramble_method: descramble_tcpdump_2018_03_15ad

        # path & name of tcpdump-files to descramble (ordered by link)
        input: [p2018.03.15crdAD_h10_lnk0.dmp, p2018.03.15crdAD_h10_lnk1.dmp]

        output_prefix: "p2018.03.15crdAD_h10"

        # older Firmware, using (pack_number) to id a packet
        descramble_tcpdump_2018_03_15ad:
            save_file: True
            clean_memory: True
            verbose: True
            multiple_save_files: True
            # multiple_metadata_file: /home/prcvlusr/PercAuxiliaryTools/PercPython/data/testFramework/2018.05.25/try1/VRST=10k_AD_10frames_meta.dat
            multiple_metadata_file: /home/prcvlusr/PercAuxiliaryTools/PercPython/data/testFramework/2018.05.25/try1/p2018.03.15crdAD_h20_meta.dat
            multiple_imgperfile: 1

            n_adc: 7
            n_grp: 212
            n_pad: 45

            n_col_in_blk: 32

        # more up-to-date Firmware, using (datatype,subframe,pack) triplet to id a packet
        descramble_tcpdump_2018_04_13aq:
            save_file: True
            clean_memory: True
            verbose: True

            multiple_save_files: True
            multiple_metadata_file: /home/marras/PERCIVAL/PercFramework/data/h5_scrmbl_view/h5in/compare_p2018.04.13crdAQ_h14.dat
            multiple_imgperfile: 1

            n_adc: 7
            n_grp: 212
            n_pad: 45

            n_col_in_blk: 32

process:
    method: process_adccal_default

    input: *output 
    input_coarse: *input_coarse
    input_fine: *input_fine
    output: *output

    process_adccal_default:
        fit_adc_part: coarse
        coarse_fitting_range: [2, 29]
        fine_fitting_range: 20 

correction:
    method: correction_adccal_default
    
    #input: *output
    #input_coarse: /Users/ben/PostDoc/P2M_HDF5/Data_lab/VRST/DLSraw/DLSraw/processed/col0-1439_processed.h5
    input_coarse: *input_coarse
    input_fine: *input_fine 
    input_gathered: /Users/ben/PostDoc/P2M_HDF5/Data_0918/Fine_scan/DLSraw/col0-1439_gathered.h5
    output: /Users/ben/PostDoc/P2M_HDF5/Data_0918/
