general:
    run_type: gather
    n_cols: 1440

    measurement: adccal

    run: &run DLSraw

    n_processes: 1

all:
    input: &input /Volumes/LACIE_SHARE/Percival/2018.12.08_3G
    output: &output /Volumes/LACIE_SHARE/Percival/2018.12.08_3G

gather:
#    method: file_per_vin_and_register_file
    method: descramble_tcpdump

    input: *input
    output: *output

    descramble_tcpdump:
        # to use it
        # (base) [prcvlusr@cfeld-percival01]~/PercAuxiliaryTools/Framework/percival-characterization% python3 ./calibration/src/analyse.py --config_file descramble_OdinDAQ_2018_06_18AY_2L2N_v01.yaml
        descramble_method: descramble_OdinDAQraw_2018_06_18AY_2L2N_v3Seq

        input: [2018.12.08_SeqMod_tint12ms_Tplus20_0802g_3Thrs_1_fl0.h5, 2018.12.08_SeqMod_tint12ms_Tplus20_0802g_3Thrs_1_fl1.h5]
        output_prefix: "2018.10.17h1527_seqMode_10hrs"

        # descramble OdinDAQ saving raw (scrambled, disordered data in 2xh5files)
        descramble_OdinDAQraw_2018_06_18AY_2L2N_v3Seq:
            # OdinDAQ as 06/2018 swaps Rst and Smpl images
            swap_sample_reset: True
            # saves descrambed to file

            # seqentialMode images taken with a standardMode-MezzFirmware? in that case, set to True
            # othwewise, set to False
            seqmode_w_stdfirm: True

            save_file: True

            multiple_save_files: True
            multiple_metadata_file: /Volumes/LACIE_SHARE/Percival/2018.12.08_3G/aux5x2_meta.dat
            multiple_imgperfile: 2

            clean_memory: True
            verbose: True
            # show descrambled images
            debug: False

        # older Firmware, using (pack_number) to id a packet
        descramble_tcpdump_2018_03_15ad:
            save_file: True
            clean_memory: True
            verbose: True
            multiple_save_files: True
            multiple_metadata_file: /home/prcvlusr/PercAuxiliaryTools/PercPython/data/testFramework/2018.05.25/try1/p2018.03.15crdAD_h20_meta.dat
            multiple_imgperfile: 1

            n_adc: 7
            n_grp: 212
            n_pad: 45

            n_col_in_blk: 32

        # more up-to-date Firmware, using (datatype,subframe,pack) triplet to id a packet
        descramble_tcpdump_2018_04_13aq:
            save_file: True
            clean_memory: True
            verbose: True

            multiple_save_files: True
            multiple_metadata_file: /home/marras/PERCIVAL/PercFramework/data/h5_scrmbl_view/h5in/compare_p2018.04.13crdAQ_h14.dat
            multiple_imgperfile: 1

            n_adc: 7
            n_grp: 212
            n_pad: 45

            n_col_in_blk: 32

process:
    method: process_pixel_calibration

    input: *input
    output: *output

    process_adccal_default:
        fit_adc_part: coarse
        coarse_fitting_range: [1, 29]

    process_pixel_calibration:
        fit_adc_part: coarse
        coarse_fitting_range: [2, 29]
